# Generated by Django 2.2.5 on 2019-09-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous_res', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rv',
            name='Rv_admin_comment',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='rv',
            name='Rv_available_date',
            field=models.DateTimeField(null=True),
        ),
    ]
