# Generated by Django 2.2.5 on 2019-09-28 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Absence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
