# Generated by Django 2.2.5 on 2019-09-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Absence', '0002_absence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='date',
            field=models.DateField(),
        ),
    ]
