# Generated by Django 2.2.5 on 2019-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantine',
            name='paye',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
