# Generated by Django 2.2.5 on 2019-09-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_cantine_paye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantine',
            name='paye',
            field=models.BooleanField(default=False),
        ),
    ]
