# Generated by Django 2.2.5 on 2019-09-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20190915_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(default='media/images/profile.png', upload_to='images/'),
        ),
    ]
