# Generated by Django 2.2.5 on 2019-11-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20190928_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
