# Generated by Django 3.1.1 on 2020-09-19 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20191106_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo_6',
        ),
    ]
